#!/bin/bash
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so
# it could be python, php, ruby, etc.

set -xe

if [ $OPENSHIFT_GEAR_NAME == "staging" ]
then
  ln -s $OPENSHIFT_DATA_DIR/public/assets $OPENSHIFT_REPO_DIR/public/assets
  cd $OPENSHIFT_REPO_DIR
  bundle exec rake assets:precompile:all RAILS_GROUPS=assets --trace
  # --trace is required to prevent slow compiles from terminating on Travis
fi

# notify Rollbar of the deployment
ACCESS_TOKEN=$ROLLBAR_ACCESS_TOKEN
LOCAL_USERNAME=`whoami`
ENVIRONMENT=$RAILS_ENV

if [ $OPENSHIFT_GEAR_NAME == "staging" ]
then
  BRANCH=develop
else
  BRANCH=master
fi

REVISION=`cat ~/git/$OPENSHIFT_GEAR_NAME.git/refs/heads/$BRANCH`

curl https://api.rollbar.com/api/1/deploy/ \
  -F access_token=$ACCESS_TOKEN \
  -F environment=$ENVIRONMENT \
  -F revision=$REVISION \
  -F local_username=$LOCAL_USERNAME
