engines:
  rubocop:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
        #mass_threshold: 30
      - javascript
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
- "**/*.min.*"
- public/**/*
- test/**/*
- "**/vendor/**/*"
