# Whether to ignore frontmatter at the beginning of HAML documents for
# frameworks such as Jekyll/Middleman
skip_frontmatter: false

linters:
  AltText:
    enabled: false

  ClassAttributeWithStaticValue:
    enabled: true

  # .class#id vs #id.class
  ClassesBeforeIds:
    enabled: false

  ConsecutiveComments:
    enabled: true

  # use :ruby block instead of multiple "-" lines
  ConsecutiveSilentScripts:
    enabled: true
    max_consecutive: 5

  EmptyScript:
    enabled: true

  HtmlAttributes:
    enabled: true

  # E.g. using lispCase instead of snake_case
  IdNames:
    enabled: false

  ImplicitDiv:
    enabled: true

  InlineStyles:
    enabled: false

  LeadingCommentSpace:
    enabled: true

  LineLength:
    enabled: false

  MultilinePipe:
    enabled: true

  MultilineScript:
    enabled: true

  ObjectReferenceAttributes:
    enabled: true

  RuboCop:
    enabled: false

  RubyComments:
    enabled: true

  SpaceBeforeScript:
    enabled: true

  # Space after/before curly brackets
  SpaceInsideHashAttributes:
    enabled: false

  TagName:
    enabled: true

  TrailingWhitespace:
    enabled: true

  UnnecessaryInterpolation:
    enabled: true

  UnnecessaryStringOutput:
    enabled: true

  ViewLength:
    enabled: false
