# Taken from Hound's defaults: https://raw.githubusercontent.com/houndci/linters/master/config/scss.yml
# Default application configuration that all configurations inherit from.

scss_files: "**/*.scss"
exclude: "app/assets/stylesheets/vendor/**"
plugin_directories: [".scss-linters"]

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

# Default severity of all linters.
severity: warning

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: false
    max_elements: 1

  # Changed from hound default
  BorderZero:
    enabled: false

  ChainedClasses:
    enabled: false

  # Changed from hound default
  ColorKeyword:
    enabled: false

  # Changed from hound default
  ColorVariable:
    enabled: false

  # Changed from hound default
  Comment:
    enabled: false
    style: silent

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DisableLinterReason:
    enabled: false

  DuplicateProperty:
    enabled: true

  ElsePlacement:
    enabled: true
    style: same_line # or 'new_line'

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  ExtendDirective:
    enabled: false

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: false
    style: short # or 'long'

  # Changed from hound default
  HexNotation:
    enabled: false

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  # Changed from hound default
  ImportantRule:
    enabled: false

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 2

  LeadingZero:
    enabled: true
    style: include_zero # or 'exclude_zero'

  MergeableSelector:
    enabled: true
    force_nesting: false # Changed from hound default

  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: hyphenated_lowercase # or 'camel_case', or 'snake_case', or a regex pattern

  NestingDepth:
    enabled: true
    max_depth: 4
    ignore_parent_selectors: false

  PlaceholderInExtend:
    enabled: false

  PrivateNamingConvention:
    enabled: false
    prefix: _

  PropertyCount:
    enabled: true
    include_nested: false
    max_properties: 15

  # Changed from hound default
  PropertySortOrder:
    enabled: false

  PropertySpelling:
    enabled: true
    extra_properties: []
    disabled_properties: []

  PropertyUnits:
    enabled: true
    global: [
        "ch",
        "em",
        "ex",
        "rem", # Font-relative lengths
        "cm",
        "in",
        "mm",
        "pc",
        "pt",
        "px",
        "q", # Absolute lengths
        "vh",
        "vw",
        "vmin",
        "vmax", # Viewport-percentage lengths
        "deg",
        "grad",
        "rad",
        "turn", # Angle
        "ms",
        "s", # Duration
        "Hz",
        "kHz", # Frequency
        "dpi",
        "dpcm",
        "dppx", # Resolution
        "%",
      ] # Other
    properties: {}

  PseudoElement:
    enabled: true

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: false
    allow_element_with_class: true
    allow_element_with_id: false

  # Changed from hound default
  SelectorDepth:
    enabled: false

  # Changed from hound default
  SelectorFormat:
    enabled: false

  # Changed from hound default
  Shorthand:
    enabled: false

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  # Changed from hound default
  SingleLinePerSelector:
    enabled: false

  SpaceAfterComma:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space'

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

  SpaceAfterPropertyName:
    enabled: true

  SpaceAfterVariableColon:
    enabled: false
    style: one_space # or 'no_space', 'at_least_one_space' or 'one_space_or_newline'

  SpaceAfterVariableName:
    enabled: true

  SpaceAroundOperator:
    enabled: true
    style: one_space # or 'at_least_one_space', or 'no_space'

  SpaceBeforeBrace:
    enabled: true
    style: space # or 'new_line'
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  # Changed from hound default
  StringQuotes:
    enabled: false
    # style: double_quotes # or single_quotes

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: true

  TrailingZero:
    enabled: false

  TransitionAll:
    enabled: false

  # Changed from hound default
  UnnecessaryMantissa:
    enabled: false

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: false
    properties: []

  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: []

  # Changed from hound default
  ZeroUnit:
    enabled: false

  Compass::*:
    enabled: false
