version: '3'
services:
  web:
    volumes:
      - ../hackathon_manager:/hackathon_manager
    environment:
      - HACKATHON_MANAGER_DEV=1
  sidekiq:
    volumes:
      - ../hackathon_manager:/hackathon_manager
    environment:
      - HACKATHON_MANAGER_DEV=1
