version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  test-build:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run build
  deploy-staging:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            .circleci/deploy_stage.sh

workflows:
  build-test:
    jobs:
      - test-build
  deploy-staging:
    triggers:
      schedule:
        filters:
          branches:
            only:
              - develop
    jobs:
      - deploy-staging
