version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run build
  deploy-staging:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy to Staging
          command: |
            git remote add deploy dokku@csh-cloud.oweb.co:brickhack-stage
            git push --force deploy develop:master
          no_output_timeout: 1h

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: develop
