version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  test-build:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run build
  deploy-staging:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            git remote add deploy dokku@csh-cloud.oweb.co:brickhack-stage
            git fetch --unshallow
            git push --force deploy develop:master

workflows:
  build-test:
    jobs:
      - test-build
  deploy-staging:
    jobs:
      - test-build
      - deploy-staging:
          requires:
            - test-build
          filters:
            branches:
              only: develop

