#!/bin/bash
# This is a manual utility script written for BrickHack to cope with OpenShift bugs.
# It acts as a manual build script, mocking what OpenShift does upon a "git push"
# Hopefully it won't be needed in the future.

# application dir
cd $OPENSHIFT_REPO_DIR

# bundle
# ln -sf $OPENSHIFT_DATA_DIR/bundle vendor/bundle
# gem uninstall rack
rm -rf vendor/cache # TODO: this is very bad. but seems to fix a bug with OpenShift
bundle install --without 'test development' --deployment

# db migration (creation if missing)
bundle exec rake db:create
bundle exec rake db:migrate

# assets precompile
# ln -sf $OPENSHIFT_DATA_DIR/assets public/assets
bundle exec rake assets:precompile

bash .openshift/action_hooks/post_deploy
