#!/bin/bash

LOCAL_USERNAME=`whoami`

curl https://api.rollbar.com/api/1/deploy/ \
  -F access_token=$ROLLBAR_ACCESS_TOKEN \
  -F environment=$ROLLBAR_ENV \
  -F revision=$GIT_REV \
  -F local_username=$LOCAL_USERNAME
