# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy - Production

on:
  push: master

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: node --version
    - name: Install dependencies
      run: npm ci
    - name: Run build script
      run: npm run build
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./build
        allow_empty_commit: true
