name: Deploy - Staging

on:
  push:
    branches:
      - develop

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop
    - name: Push to Staging
      uses: dokku/github-action@master
      with:
        git_push_flags: '--force'
        git_remote_url: 'ssh://dokku@csh-cloud.oweb.co:22/brickhack-stage'
        ssh_private_key: ${{ secrets.CODERIT_CLOUD_SSH_PRIVATE_KEY }}
