# Deploys a preview page for each PR on FeaturePeek

name: Deploy - Staging

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
      env:
        IDENTITY_POOL_ID: ${{ secrets.IDENTITY_POOL_ID }}
    - name: Ping FeaturePeek
      run: bash <(curl -s https://peek.run/ci)
