# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy - Staging

on:
  push:
    branches:
      - develop

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop
    - name: Push to Staging
      uses: dokku/github-action@master
      with:
        git_remote_url: 'dokku@csh-cloud.oweb.co:brickhack-stage'
        ssh_private_key: ${{ secrets.CODERIT_CLOUD_SSH_PRIVATE_KEY }}
